version: '3'
services:
  web:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs/:/var/log/nginx/
      - ./../services/frontend:/var/www/html/frontend
      #- ./nginx/default.template.conf:/etc/nginx/conf.d/default.template
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    #command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: unless-stopped
    depends_on:
      - php
      - mysqldb
  php:
    image: nanoninja/php-fpm:${PHP_VERSION}
    restart: unless-stopped
    #command: php /var/www/html/chat_api/server.php start
    volumes:
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
      #- ./../services/user_api:/var/www/html/user_api
      #- ./../services/frontend:/var/www/html/frontend
      #- ./../services/chat_api:/var/www/html/chat_api
      - ./../services/:/var/www/html/
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    env_file:
      - ".env"
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${MYSQL_HOST}
    restart: unless-stopped
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:${MYSQL_VERSION}
    container_name: ${MYSQL_HOST}
    #command: --init-file /data/application/init.sql
    restart: unless-stopped
    env_file:
      - ".env"
    environment:
      #- MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "8989:3306"
    volumes:
      - ./mysql:/var/lib/mysql
  #centrifugo:
  #  image: centrifugo/centrifugo:v3
  #  volumes:
  #    - ./centrifugo/config.json:/centrifugo/config.json
  #  command: centrifugo -c config.json --port=8081
  #  ports:
  #    - "8081:8081"